apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: docker.io/redis:4.0
        command: ["redis-server", "--slaveof", "127.0.0.1", "2000"]
        resources:
          requests:
            cpu: 80m
            memory: 100Mi
        ports:
        - containerPort: 6379
      - name: alpine
        image: docker.io/ctslater/alpine-ssh
        command: ["ssh", "-i", "/keys/forwarding_key", "-N", "-L", "2000:localhost:6379", "ctslater@epyc.astro.washington.edu"]
        volumeMounts:
        - name: keys
          mountPath: "/keys"
          readOnly: true
        resources:
          requests:
            cpu: 20m
            memory: 40Mi
        ports:
        - containerPort: 2000
      volumes:
      - name: keys
        secret:
          secretName: ssh-key
          defaultMode: 256
